# Generated by Django 4.2.7 on 2023-12-15 21:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="role",
            name="name",
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="national_id",
            field=models.CharField(
                max_length=10,
                unique=True,
                validators=[
                    django.core.validators.MaxLengthValidator(
                        limit_value=10,
                        message="National ID should be exactly 10 characters.",
                    ),
                    django.core.validators.MinLengthValidator(
                        limit_value=10,
                        message="National ID should be exactly 10 characters.",
                    ),
                ],
            ),
        ),
    ]
