# Generated by Django 4.2.7 on 2023-11-20 22:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "admin"),
                    ("doctor", "doctor"),
                    ("patient", "patient"),
                ],
                default="patient",
                max_length=10,
            ),
        ),
    ]
