# Generated by Django 4.2.7 on 2024-01-28 10:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('m', 'male'), ('f', 'female'), ('n', 'known')], default='n', verbose_name='gender'),
        ),
        migrations.AlterField(
            model_name='user',
            name='national_id',
            field=models.CharField(max_length=10, unique=True, validators=[django.core.validators.MaxLengthValidator(limit_value=10, message='National ID should be exactly 10 characters.'), django.core.validators.MinLengthValidator(limit_value=10, message='National ID should be exactly 10 characters.')], verbose_name='national_id'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_no',
            field=models.CharField(max_length=11, unique=True, validators=[django.core.validators.MaxLengthValidator(limit_value=11, message='Phone Number should be exactly 10 or 11 characters.'), django.core.validators.MinLengthValidator(limit_value=10, message='Phone Number should be exactly 10 or 11 characters.')], verbose_name='phone_no'),
        ),
    ]
