# Generated by Django 4.2.7 on 2023-11-28 13:06

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField()),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("completed", "completed"),
                            ("canceled", "canceled"),
                            ("reserved", "reserved"),
                        ],
                        default="canceled",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("face to face", "face to face"),
                            ("online", "online"),
                        ],
                        default="online",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Assurance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name="Doctor",
            fields=[
                (
                    "user_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("medical_system_number", models.IntegerField()),
                ("fees", models.FloatField()),
                ("slice", models.IntegerField(default=30)),
            ],
            options={
                "verbose_name": "doctor",
                "verbose_name_plural": "doctors",
            },
            bases=("authentication.user",),
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Medicine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("generic_name", models.CharField(blank=True, null=True)),
                ("infant_safe", models.BooleanField(default=True)),
                ("price", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="PatientMedicalHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "blood_group",
                    models.CharField(
                        choices=[
                            ("A+", "A Positive"),
                            ("A-", "A Negative"),
                            ("B-", "B Negative"),
                            ("B+", "B Positive"),
                            ("O+", "O Positive"),
                            ("O-", "O Negative"),
                            ("AB-", "AB Negative"),
                            ("AB+", "AB Positive"),
                        ],
                        max_length=3,
                    ),
                ),
                ("blood_pressure", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Speciality",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
            ],
            options={
                "verbose_name": "Speciality",
                "verbose_name_plural": "Specialities",
            },
        ),
        migrations.CreateModel(
            name="TimeSlice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(null=True)),
                ("start", models.TimeField(null=True)),
                ("end", models.TimeField(null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("available", "available"),
                            ("unavailable", "unavailable"),
                        ],
                        default="unavailable",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Prescription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("is_expired", models.BooleanField(default=False)),
                ("date", models.DateField()),
                (
                    "appointment_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="appointment.appointment",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "user_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "assurance",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="appointment.assurance",
                    ),
                ),
                (
                    "medical_history",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="appointment.patientmedicalhistory",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "abstract": False,
            },
            bases=("authentication.user",),
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="DoctorTime",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "doctor_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="appointment.doctor",
                    ),
                ),
                (
                    "timeslice_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="appointment.timeslice",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="doctor",
            name="speciality",
            field=models.ManyToManyField(to="appointment.speciality"),
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("treatment_experience", models.TextField(blank=True, null=True)),
                ("recommend_to_other", models.BooleanField()),
                ("point", models.IntegerField()),
                (
                    "doctor_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="appointment.doctor",
                    ),
                ),
                (
                    "patient_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="appointment.patient",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AppointmentTime",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "appointment_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="appointment.appointment",
                    ),
                ),
                (
                    "timeslice_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="appointment.timeslice",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="appointment",
            name="doctor_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="appointment.doctor"
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="patient_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="appointment.patient"
            ),
        ),
    ]
