# Generated by Django 4.2.7 on 2023-11-27 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("appointment", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient",
            name="medical_history",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="appointment.patientmedicalhistory",
            ),
        ),
    ]
