# Generated by Django 4.2.7 on 2023-12-13 09:27

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("appointment", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="appointmenttime",
            options={"verbose_name_plural": "appointment times"},
        ),
        migrations.AlterModelOptions(
            name="comment",
            options={"ordering": ["created"]},
        ),
        migrations.AlterModelOptions(
            name="doctortime",
            options={"verbose_name_plural": "doctor times"},
        ),
        migrations.AlterModelOptions(
            name="patient",
            options={"verbose_name": "patient", "verbose_name_plural": "patients"},
        ),
        migrations.AlterModelOptions(
            name="patientmedicalhistory",
            options={
                "verbose_name": "medical history",
                "verbose_name_plural": "medical histories",
            },
        ),
        migrations.RemoveField(
            model_name="appointmenttime",
            name="id",
        ),
        migrations.RemoveField(
            model_name="appointmenttime",
            name="timeslice_id",
        ),
        migrations.RemoveField(
            model_name="comment",
            name="recommend_to_other",
        ),
        migrations.RemoveField(
            model_name="doctortime",
            name="id",
        ),
        migrations.RemoveField(
            model_name="doctortime",
            name="timeslice_id",
        ),
        migrations.AddField(
            model_name="appointmenttime",
            name="timeslice_ptr",
            field=models.OneToOneField(
                auto_created=True,
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                parent_link=True,
                primary_key=True,
                serialize=False,
                to="appointment.timeslice",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="comment",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="doctortime",
            name="timeslice_ptr",
            field=models.OneToOneField(
                auto_created=True,
                default=123,
                on_delete=django.db.models.deletion.CASCADE,
                parent_link=True,
                primary_key=True,
                serialize=False,
                to="appointment.timeslice",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="patientmedicalhistory",
            name="height",
            field=models.FloatField(default=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="patientmedicalhistory",
            name="weight",
            field=models.FloatField(default=12),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="appointment",
            name="doctor_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="appointment.doctor"
            ),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="patient_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="appointment.patient"
            ),
        ),
        migrations.AlterField(
            model_name="appointmenttime",
            name="appointment_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="appointment_times",
                to="appointment.appointment",
            ),
        ),
        migrations.AlterField(
            model_name="assurance",
            name="name",
            field=models.CharField(max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name="comment",
            name="doctor_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="appointment.doctor",
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="patient_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="appointment.patient",
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="point",
            field=models.IntegerField(
                default=1,
                validators=[
                    django.core.validators.MaxValueValidator(5),
                    django.core.validators.MinValueValidator(1),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="doctor",
            name="medical_system_number",
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name="doctortime",
            name="doctor_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="doctor_times",
                to="appointment.doctor",
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="medical_history",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="appointment.patientmedicalhistory",
            ),
        ),
        migrations.AlterField(
            model_name="prescription",
            name="appointment_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="appointment.appointment",
            ),
        ),
        migrations.AddIndex(
            model_name="comment",
            index=models.Index(
                fields=["created"], name="appointment_created_26ca88_idx"
            ),
        ),
    ]
