# Generated by Django 4.2.7 on 2023-12-15 21:32

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        (
            "appointment",
            "0002_alter_appointmenttime_options_alter_comment_options_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="patient_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="appointments",
                to="appointment.patient",
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="medical_history",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="appointment.patientmedicalhistory",
            ),
        ),
        migrations.AlterField(
            model_name="patientmedicalhistory",
            name="blood_group",
            field=models.CharField(
                blank=True,
                choices=[
                    ("A+", "A Positive"),
                    ("A-", "A Negative"),
                    ("B-", "B Negative"),
                    ("B+", "B Positive"),
                    ("O+", "O Positive"),
                    ("O-", "O Negative"),
                    ("AB-", "AB Negative"),
                    ("AB+", "AB Positive"),
                ],
                default="A+",
                max_length=3,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="patientmedicalhistory",
            name="blood_pressure",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="patientmedicalhistory",
            name="height",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="patientmedicalhistory",
            name="weight",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="prescription",
            name="appointment_id",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="prescription",
                to="appointment.appointment",
            ),
        ),
        migrations.AlterField(
            model_name="timeslice",
            name="date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.RemoveField(model_name="timeslice", name="end"),
        migrations.RemoveField(model_name="timeslice", name="start"),
        migrations.AddField(
            model_name="timeslice",
            name="end",
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name="timeslice",
            name="start",
            field=models.IntegerField(default=-1),
        ),
    ]
