# Generated by Django 4.2.7 on 2023-12-15 21:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("appointment", "0004_alter_timeslice_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="timeslice",
            name="date",
            field=models.DateField(default=datetime.date.today),
        ),
    ]
