# Generated by Django 4.2.7 on 2023-12-15 22:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("appointment", "0005_alter_timeslice_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="appointment",
            name="date",
        ),
        migrations.RemoveField(
            model_name="appointmenttime",
            name="appointment_id",
        ),
        migrations.AddField(
            model_name="appointment",
            name="appointment_time",
            field=models.ForeignKey(
                default=-1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="appointments",
                to="appointment.appointmenttime",
            ),
        ),
    ]
