# Generated by Django 4.2.7 on 2023-12-16 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("appointment", "0006_remove_appointment_date_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="doctortime",
            name="doctor_id",
        ),
        migrations.RemoveField(
            model_name="doctortime",
            name="timeslice_ptr",
        ),
        migrations.AddField(
            model_name="timeslice",
            name="doctor",
            field=models.ForeignKey(
                default=8,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="available_time_slices",
                to="appointment.doctor",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="appointment",
            name="appointment_time",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="appointment",
                to="appointment.timeslice",
            ),
        ),
        migrations.DeleteModel(
            name="AppointmentTime",
        ),
        migrations.DeleteModel(
            name="DoctorTime",
        ),
    ]
