# Generated by Django 4.2.7 on 2023-12-16 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("appointment", "0007_remove_doctortime_doctor_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="description",
            field=models.TextField(blank=True, default="-", null=True),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="doctor_id",
            field=models.ForeignKey(
                default=-1,
                on_delete=django.db.models.deletion.CASCADE,
                to="appointment.doctor",
            ),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="status",
            field=models.CharField(
                choices=[
                    ("reserved", "reserved"),
                    ("completed", "completed"),
                    ("canceled", "canceled"),
                ],
                default="reserved",
            ),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="type",
            field=models.CharField(
                choices=[("face to face", "face to face"), ("online", "online")],
                default="face to face",
            ),
        ),
    ]
