# Generated by Django 4.2.7 on 2023-12-18 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("appointment", "0008_alter_appointment_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="doctor_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="appointment.doctor"
            ),
        ),
    ]
