name: Build Docker Container after Django Test

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test_django:
    uses: saraAhangari/software-engineering-project/.github/workflows/django-test.yaml@master
  container_builder:
    runs-on: ubuntu-latest
    needs: [test_django]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build container image
        run: |
          docker build \
          -t saraAhangari/app:${GITHUB_SHA::7} \
          -t saraAhangari/app:latest \
          .

